CREATE TABLE "games" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "summary" varchar NOT NULL,
  "release_date" date NOT NULL,
  "image" varchar,
  "site" varchar,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "platforms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "studios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) UNIQUE NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz,
  "deleted_at" timestamptz
);

CREATE TABLE "games_platforms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" integer,
  "platform_id" integer,
  "game_name" varchar NOT NULL,
  "platform_name" varchar NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz
);

CREATE TABLE "games_studios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" integer,
  "studio_id" integer,
  "game_name" varchar NOT NULL,
  "studio_name" varchar NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz
);

COMMENT ON TABLE "games_platforms" IS 'Denormalization from games and platforms. Create indexes in the future.';

COMMENT ON TABLE "games_studios" IS 'Denormalization from games and studios. Create indexes in the future.';

ALTER TABLE "games_platforms" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "games_platforms" ADD FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id");

ALTER TABLE "games_studios" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "games_studios" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id");
