controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v1:
    resource:
        path: ../src/Controller/V1
        namespace: App\Controller\V1
    type: attribute
    prefix: '/api/v1'
